'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("0998d9ae-eb57-43a8-9b22-c45d41a5c902"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("InventoryModel", "FK_PenerimaanBarang_Barang", "Barang", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Barang), "PenerimaanBarang", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PenerimaanBarang)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("InventoryModel", "FK_PengeluaranBarang_Barang", "Barang", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Barang), "PengeluaranBarang", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PengeluaranBarang)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("InventoryModel", "FK_PengeluaranBarang_Customer", "Customer", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Customer), "PengeluaranBarang", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PengeluaranBarang)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("InventoryModel", "FK_PenerimaanBarang_Supplier", "Supplier", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Supplier), "PenerimaanBarang", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PenerimaanBarang))> 

'Original file name:
'Generation date: 2/24/2013 11:26:06 PM
'''<summary>
'''There are no comments for InventoryArcomaBascoEntities2 in the schema.
'''</summary>
Partial Public Class InventoryArcomaBascoEntities2
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new InventoryArcomaBascoEntities2 object using the connection string found in the 'InventoryArcomaBascoEntities2' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=InventoryArcomaBascoEntities2", "InventoryArcomaBascoEntities2")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new InventoryArcomaBascoEntities2 object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "InventoryArcomaBascoEntities2")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new InventoryArcomaBascoEntities2 object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "InventoryArcomaBascoEntities2")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for Barang in the schema.
    '''</summary>
    Public ReadOnly Property Barang() As Global.System.Data.Objects.ObjectQuery(Of Barang)
        Get
            If (Me._Barang Is Nothing) Then
                Me._Barang = MyBase.CreateQuery(Of Barang)("[Barang]")
            End If
            Return Me._Barang
        End Get
    End Property
    Private _Barang As Global.System.Data.Objects.ObjectQuery(Of Barang)
    '''<summary>
    '''There are no comments for Customer in the schema.
    '''</summary>
    Public ReadOnly Property Customer() As Global.System.Data.Objects.ObjectQuery(Of Customer)
        Get
            If (Me._Customer Is Nothing) Then
                Me._Customer = MyBase.CreateQuery(Of Customer)("[Customer]")
            End If
            Return Me._Customer
        End Get
    End Property
    Private _Customer As Global.System.Data.Objects.ObjectQuery(Of Customer)
    '''<summary>
    '''There are no comments for PenerimaanBarang in the schema.
    '''</summary>
    Public ReadOnly Property PenerimaanBarang() As Global.System.Data.Objects.ObjectQuery(Of PenerimaanBarang)
        Get
            If (Me._PenerimaanBarang Is Nothing) Then
                Me._PenerimaanBarang = MyBase.CreateQuery(Of PenerimaanBarang)("[PenerimaanBarang]")
            End If
            Return Me._PenerimaanBarang
        End Get
    End Property
    Private _PenerimaanBarang As Global.System.Data.Objects.ObjectQuery(Of PenerimaanBarang)
    '''<summary>
    '''There are no comments for PengeluaranBarang in the schema.
    '''</summary>
    Public ReadOnly Property PengeluaranBarang() As Global.System.Data.Objects.ObjectQuery(Of PengeluaranBarang)
        Get
            If (Me._PengeluaranBarang Is Nothing) Then
                Me._PengeluaranBarang = MyBase.CreateQuery(Of PengeluaranBarang)("[PengeluaranBarang]")
            End If
            Return Me._PengeluaranBarang
        End Get
    End Property
    Private _PengeluaranBarang As Global.System.Data.Objects.ObjectQuery(Of PengeluaranBarang)
    '''<summary>
    '''There are no comments for Supplier in the schema.
    '''</summary>
    Public ReadOnly Property Supplier() As Global.System.Data.Objects.ObjectQuery(Of Supplier)
        Get
            If (Me._Supplier Is Nothing) Then
                Me._Supplier = MyBase.CreateQuery(Of Supplier)("[Supplier]")
            End If
            Return Me._Supplier
        End Get
    End Property
    Private _Supplier As Global.System.Data.Objects.ObjectQuery(Of Supplier)
    '''<summary>
    '''There are no comments for Barang in the schema.
    '''</summary>
    Public Sub AddToBarang(ByVal barang As Barang)
        MyBase.AddObject("Barang", barang)
    End Sub
    '''<summary>
    '''There are no comments for Customer in the schema.
    '''</summary>
    Public Sub AddToCustomer(ByVal customer As Customer)
        MyBase.AddObject("Customer", customer)
    End Sub
    '''<summary>
    '''There are no comments for PenerimaanBarang in the schema.
    '''</summary>
    Public Sub AddToPenerimaanBarang(ByVal penerimaanBarang As PenerimaanBarang)
        MyBase.AddObject("PenerimaanBarang", penerimaanBarang)
    End Sub
    '''<summary>
    '''There are no comments for PengeluaranBarang in the schema.
    '''</summary>
    Public Sub AddToPengeluaranBarang(ByVal pengeluaranBarang As PengeluaranBarang)
        MyBase.AddObject("PengeluaranBarang", pengeluaranBarang)
    End Sub
    '''<summary>
    '''There are no comments for Supplier in the schema.
    '''</summary>
    Public Sub AddToSupplier(ByVal supplier As Supplier)
        MyBase.AddObject("Supplier", supplier)
    End Sub
End Class
'''<summary>
'''There are no comments for InventoryModel.Barang in the schema.
'''</summary>
'''<KeyProperties>
'''Kode_Barang
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="InventoryModel", Name:="Barang"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Barang
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Barang object.
    '''</summary>
    '''<param name="kode_Barang">Initial value of Kode_Barang.</param>
    '''<param name="nama_Barang">Initial value of Nama_Barang.</param>
    '''<param name="stock_Barang">Initial value of Stock_Barang.</param>
    '''<param name="harga_Barang">Initial value of Harga_Barang.</param>
    Public Shared Function CreateBarang(ByVal kode_Barang As String, ByVal nama_Barang As String, ByVal stock_Barang As Integer, ByVal harga_Barang As Integer) As Barang
        Dim barang As Barang = New Barang
        barang.Kode_Barang = kode_Barang
        barang.Nama_Barang = nama_Barang
        barang.Stock_Barang = stock_Barang
        barang.Harga_Barang = harga_Barang
        Return barang
    End Function
    '''<summary>
    '''There are no comments for Property Kode_Barang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Kode_Barang() As String
        Get
            Return Me._Kode_Barang
        End Get
        Set
            Me.OnKode_BarangChanging(value)
            Me.ReportPropertyChanging("Kode_Barang")
            Me._Kode_Barang = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Kode_Barang")
            Me.OnKode_BarangChanged
        End Set
    End Property
    Private _Kode_Barang As String
    Partial Private Sub OnKode_BarangChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKode_BarangChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nama_Barang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nama_Barang() As String
        Get
            Return Me._Nama_Barang
        End Get
        Set
            Me.OnNama_BarangChanging(value)
            Me.ReportPropertyChanging("Nama_Barang")
            Me._Nama_Barang = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nama_Barang")
            Me.OnNama_BarangChanged
        End Set
    End Property
    Private _Nama_Barang As String
    Partial Private Sub OnNama_BarangChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNama_BarangChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Stock_Barang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Stock_Barang() As Integer
        Get
            Return Me._Stock_Barang
        End Get
        Set
            Me.OnStock_BarangChanging(value)
            Me.ReportPropertyChanging("Stock_Barang")
            Me._Stock_Barang = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Stock_Barang")
            Me.OnStock_BarangChanged
        End Set
    End Property
    Private _Stock_Barang As Integer
    Partial Private Sub OnStock_BarangChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnStock_BarangChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Harga_Barang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Harga_Barang() As Integer
        Get
            Return Me._Harga_Barang
        End Get
        Set
            Me.OnHarga_BarangChanging(value)
            Me.ReportPropertyChanging("Harga_Barang")
            Me._Harga_Barang = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Harga_Barang")
            Me.OnHarga_BarangChanged
        End Set
    End Property
    Private _Harga_Barang As Integer
    Partial Private Sub OnHarga_BarangChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnHarga_BarangChanged()
        End Sub
    '''<summary>
    '''There are no comments for PenerimaanBarang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PenerimaanBarang_Barang", "PenerimaanBarang"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PenerimaanBarang() As Global.System.Data.Objects.DataClasses.EntityCollection(Of PenerimaanBarang)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PenerimaanBarang)("InventoryModel.FK_PenerimaanBarang_Barang", "PenerimaanBarang")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PenerimaanBarang)("InventoryModel.FK_PenerimaanBarang_Barang", "PenerimaanBarang", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for PengeluaranBarang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PengeluaranBarang_Barang", "PengeluaranBarang"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PengeluaranBarang() As Global.System.Data.Objects.DataClasses.EntityCollection(Of PengeluaranBarang)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PengeluaranBarang)("InventoryModel.FK_PengeluaranBarang_Barang", "PengeluaranBarang")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PengeluaranBarang)("InventoryModel.FK_PengeluaranBarang_Barang", "PengeluaranBarang", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for InventoryModel.Customer in the schema.
'''</summary>
'''<KeyProperties>
'''Kode_Customer
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="InventoryModel", Name:="Customer"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Customer
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Customer object.
    '''</summary>
    '''<param name="kode_Customer">Initial value of Kode_Customer.</param>
    '''<param name="nama_Customer">Initial value of Nama_Customer.</param>
    Public Shared Function CreateCustomer(ByVal kode_Customer As String, ByVal nama_Customer As String) As Customer
        Dim customer As Customer = New Customer
        customer.Kode_Customer = kode_Customer
        customer.Nama_Customer = nama_Customer
        Return customer
    End Function
    '''<summary>
    '''There are no comments for Property Kode_Customer in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Kode_Customer() As String
        Get
            Return Me._Kode_Customer
        End Get
        Set
            Me.OnKode_CustomerChanging(value)
            Me.ReportPropertyChanging("Kode_Customer")
            Me._Kode_Customer = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Kode_Customer")
            Me.OnKode_CustomerChanged
        End Set
    End Property
    Private _Kode_Customer As String
    Partial Private Sub OnKode_CustomerChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKode_CustomerChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nama_Customer in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nama_Customer() As String
        Get
            Return Me._Nama_Customer
        End Get
        Set
            Me.OnNama_CustomerChanging(value)
            Me.ReportPropertyChanging("Nama_Customer")
            Me._Nama_Customer = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nama_Customer")
            Me.OnNama_CustomerChanged
        End Set
    End Property
    Private _Nama_Customer As String
    Partial Private Sub OnNama_CustomerChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNama_CustomerChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Alamat in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Alamat() As String
        Get
            Return Me._Alamat
        End Get
        Set
            Me.OnAlamatChanging(value)
            Me.ReportPropertyChanging("Alamat")
            Me._Alamat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Alamat")
            Me.OnAlamatChanged
        End Set
    End Property
    Private _Alamat As String
    Partial Private Sub OnAlamatChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAlamatChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Telephone in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Telephone() As String
        Get
            Return Me._Telephone
        End Get
        Set
            Me.OnTelephoneChanging(value)
            Me.ReportPropertyChanging("Telephone")
            Me._Telephone = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Telephone")
            Me.OnTelephoneChanged
        End Set
    End Property
    Private _Telephone As String
    Partial Private Sub OnTelephoneChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnTelephoneChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Email in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Email() As String
        Get
            Return Me._Email
        End Get
        Set
            Me.OnEmailChanging(value)
            Me.ReportPropertyChanging("Email")
            Me._Email = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Email")
            Me.OnEmailChanged
        End Set
    End Property
    Private _Email As String
    Partial Private Sub OnEmailChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnEmailChanged()
        End Sub
    '''<summary>
    '''There are no comments for PengeluaranBarang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PengeluaranBarang_Customer", "PengeluaranBarang"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PengeluaranBarang() As Global.System.Data.Objects.DataClasses.EntityCollection(Of PengeluaranBarang)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PengeluaranBarang)("InventoryModel.FK_PengeluaranBarang_Customer", "PengeluaranBarang")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PengeluaranBarang)("InventoryModel.FK_PengeluaranBarang_Customer", "PengeluaranBarang", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for InventoryModel.PenerimaanBarang in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="InventoryModel", Name:="PenerimaanBarang"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class PenerimaanBarang
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new PenerimaanBarang object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="no_Invoice">Initial value of No_Invoice.</param>
    '''<param name="tanggal">Initial value of Tanggal.</param>
    '''<param name="jumlah">Initial value of Jumlah.</param>
    Public Shared Function CreatePenerimaanBarang(ByVal id As Integer, ByVal no_Invoice As String, ByVal tanggal As Date, ByVal jumlah As Integer) As PenerimaanBarang
        Dim penerimaanBarang As PenerimaanBarang = New PenerimaanBarang
        penerimaanBarang.Id = id
        penerimaanBarang.No_Invoice = no_Invoice
        penerimaanBarang.Tanggal = tanggal
        penerimaanBarang.Jumlah = jumlah
        Return penerimaanBarang
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As Integer
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As Integer
    Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property No_Invoice in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property No_Invoice() As String
        Get
            Return Me._No_Invoice
        End Get
        Set
            Me.OnNo_InvoiceChanging(value)
            Me.ReportPropertyChanging("No_Invoice")
            Me._No_Invoice = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("No_Invoice")
            Me.OnNo_InvoiceChanged
        End Set
    End Property
    Private _No_Invoice As String
    Partial Private Sub OnNo_InvoiceChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNo_InvoiceChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Tanggal in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Tanggal() As Date
        Get
            Return Me._Tanggal
        End Get
        Set
            Me.OnTanggalChanging(value)
            Me.ReportPropertyChanging("Tanggal")
            Me._Tanggal = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Tanggal")
            Me.OnTanggalChanged
        End Set
    End Property
    Private _Tanggal As Date
    Partial Private Sub OnTanggalChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnTanggalChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Jumlah in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Jumlah() As Integer
        Get
            Return Me._Jumlah
        End Get
        Set
            Me.OnJumlahChanging(value)
            Me.ReportPropertyChanging("Jumlah")
            Me._Jumlah = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Jumlah")
            Me.OnJumlahChanged
        End Set
    End Property
    Private _Jumlah As Integer
    Partial Private Sub OnJumlahChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnJumlahChanged()
        End Sub
    '''<summary>
    '''There are no comments for Barang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PenerimaanBarang_Barang", "Barang"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Barang() As Barang
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Barang)("InventoryModel.FK_PenerimaanBarang_Barang", "Barang").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Barang)("InventoryModel.FK_PenerimaanBarang_Barang", "Barang").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Barang in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property BarangReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Barang)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Barang)("InventoryModel.FK_PenerimaanBarang_Barang", "Barang")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Barang)("InventoryModel.FK_PenerimaanBarang_Barang", "Barang", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Supplier in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PenerimaanBarang_Supplier", "Supplier"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Supplier() As Supplier
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Supplier)("InventoryModel.FK_PenerimaanBarang_Supplier", "Supplier").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Supplier)("InventoryModel.FK_PenerimaanBarang_Supplier", "Supplier").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Supplier in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property SupplierReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Supplier)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Supplier)("InventoryModel.FK_PenerimaanBarang_Supplier", "Supplier")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Supplier)("InventoryModel.FK_PenerimaanBarang_Supplier", "Supplier", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for InventoryModel.PengeluaranBarang in the schema.
'''</summary>
'''<KeyProperties>
'''Id
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="InventoryModel", Name:="PengeluaranBarang"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class PengeluaranBarang
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new PengeluaranBarang object.
    '''</summary>
    '''<param name="id">Initial value of Id.</param>
    '''<param name="no_Dokumen">Initial value of No_Dokumen.</param>
    '''<param name="tanggal">Initial value of Tanggal.</param>
    '''<param name="jumlah">Initial value of Jumlah.</param>
    Public Shared Function CreatePengeluaranBarang(ByVal id As Integer, ByVal no_Dokumen As String, ByVal tanggal As Date, ByVal jumlah As Integer) As PengeluaranBarang
        Dim pengeluaranBarang As PengeluaranBarang = New PengeluaranBarang
        pengeluaranBarang.Id = id
        pengeluaranBarang.No_Dokumen = no_Dokumen
        pengeluaranBarang.Tanggal = tanggal
        pengeluaranBarang.Jumlah = jumlah
        Return pengeluaranBarang
    End Function
    '''<summary>
    '''There are no comments for Property Id in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Id() As Integer
        Get
            Return Me._Id
        End Get
        Set
            Me.OnIdChanging(value)
            Me.ReportPropertyChanging("Id")
            Me._Id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Id")
            Me.OnIdChanged
        End Set
    End Property
    Private _Id As Integer
    Partial Private Sub OnIdChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnIdChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property No_Dokumen in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property No_Dokumen() As String
        Get
            Return Me._No_Dokumen
        End Get
        Set
            Me.OnNo_DokumenChanging(value)
            Me.ReportPropertyChanging("No_Dokumen")
            Me._No_Dokumen = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("No_Dokumen")
            Me.OnNo_DokumenChanged
        End Set
    End Property
    Private _No_Dokumen As String
    Partial Private Sub OnNo_DokumenChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNo_DokumenChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Tanggal in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Tanggal() As Date
        Get
            Return Me._Tanggal
        End Get
        Set
            Me.OnTanggalChanging(value)
            Me.ReportPropertyChanging("Tanggal")
            Me._Tanggal = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Tanggal")
            Me.OnTanggalChanged
        End Set
    End Property
    Private _Tanggal As Date
    Partial Private Sub OnTanggalChanging(ByVal value As Date)
        End Sub
    Partial Private Sub OnTanggalChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Jumlah in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Jumlah() As Integer
        Get
            Return Me._Jumlah
        End Get
        Set
            Me.OnJumlahChanging(value)
            Me.ReportPropertyChanging("Jumlah")
            Me._Jumlah = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Jumlah")
            Me.OnJumlahChanged
        End Set
    End Property
    Private _Jumlah As Integer
    Partial Private Sub OnJumlahChanging(ByVal value As Integer)
        End Sub
    Partial Private Sub OnJumlahChanged()
        End Sub
    '''<summary>
    '''There are no comments for Barang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PengeluaranBarang_Barang", "Barang"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Barang() As Barang
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Barang)("InventoryModel.FK_PengeluaranBarang_Barang", "Barang").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Barang)("InventoryModel.FK_PengeluaranBarang_Barang", "Barang").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Barang in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property BarangReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Barang)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Barang)("InventoryModel.FK_PengeluaranBarang_Barang", "Barang")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Barang)("InventoryModel.FK_PengeluaranBarang_Barang", "Barang", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Customer in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PengeluaranBarang_Customer", "Customer"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Customer() As Customer
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("InventoryModel.FK_PengeluaranBarang_Customer", "Customer").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("InventoryModel.FK_PengeluaranBarang_Customer", "Customer").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Customer in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property CustomerReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Customer)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Customer)("InventoryModel.FK_PengeluaranBarang_Customer", "Customer")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Customer)("InventoryModel.FK_PengeluaranBarang_Customer", "Customer", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for InventoryModel.Supplier in the schema.
'''</summary>
'''<KeyProperties>
'''Kode_Supplier
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="InventoryModel", Name:="Supplier"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Supplier
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Supplier object.
    '''</summary>
    '''<param name="kode_Supplier">Initial value of Kode_Supplier.</param>
    '''<param name="nama_Supplier">Initial value of Nama_Supplier.</param>
    Public Shared Function CreateSupplier(ByVal kode_Supplier As String, ByVal nama_Supplier As String) As Supplier
        Dim supplier As Supplier = New Supplier
        supplier.Kode_Supplier = kode_Supplier
        supplier.Nama_Supplier = nama_Supplier
        Return supplier
    End Function
    '''<summary>
    '''There are no comments for Property Kode_Supplier in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Kode_Supplier() As String
        Get
            Return Me._Kode_Supplier
        End Get
        Set
            Me.OnKode_SupplierChanging(value)
            Me.ReportPropertyChanging("Kode_Supplier")
            Me._Kode_Supplier = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Kode_Supplier")
            Me.OnKode_SupplierChanged
        End Set
    End Property
    Private _Kode_Supplier As String
    Partial Private Sub OnKode_SupplierChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnKode_SupplierChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Nama_Supplier in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Nama_Supplier() As String
        Get
            Return Me._Nama_Supplier
        End Get
        Set
            Me.OnNama_SupplierChanging(value)
            Me.ReportPropertyChanging("Nama_Supplier")
            Me._Nama_Supplier = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nama_Supplier")
            Me.OnNama_SupplierChanged
        End Set
    End Property
    Private _Nama_Supplier As String
    Partial Private Sub OnNama_SupplierChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnNama_SupplierChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Alamat in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Alamat() As String
        Get
            Return Me._Alamat
        End Get
        Set
            Me.OnAlamatChanging(value)
            Me.ReportPropertyChanging("Alamat")
            Me._Alamat = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Alamat")
            Me.OnAlamatChanged
        End Set
    End Property
    Private _Alamat As String
    Partial Private Sub OnAlamatChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnAlamatChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Telepon in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Telepon() As String
        Get
            Return Me._Telepon
        End Get
        Set
            Me.OnTeleponChanging(value)
            Me.ReportPropertyChanging("Telepon")
            Me._Telepon = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Telepon")
            Me.OnTeleponChanged
        End Set
    End Property
    Private _Telepon As String
    Partial Private Sub OnTeleponChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnTeleponChanged()
        End Sub
    '''<summary>
    '''There are no comments for Property Email in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Email() As String
        Get
            Return Me._Email
        End Get
        Set
            Me.OnEmailChanging(value)
            Me.ReportPropertyChanging("Email")
            Me._Email = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Email")
            Me.OnEmailChanged
        End Set
    End Property
    Private _Email As String
    Partial Private Sub OnEmailChanging(ByVal value As String)
        End Sub
    Partial Private Sub OnEmailChanged()
        End Sub
    '''<summary>
    '''There are no comments for PenerimaanBarang in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("InventoryModel", "FK_PenerimaanBarang_Supplier", "PenerimaanBarang"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property PenerimaanBarang() As Global.System.Data.Objects.DataClasses.EntityCollection(Of PenerimaanBarang)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PenerimaanBarang)("InventoryModel.FK_PenerimaanBarang_Supplier", "PenerimaanBarang")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PenerimaanBarang)("InventoryModel.FK_PenerimaanBarang_Supplier", "PenerimaanBarang", value)
            End If
        End Set
    End Property
End Class
